### PR TITLE
docs: exemple to use buttons

### PR DESCRIPTION
**Pull request by joaosouz4dev**
Fixes # .

## Changes proposed in this pull request

-
-

To test (it takes a while): `npm install github:<username>/wppconnect#<branch>`

### CODE REVIEW

**Comment by Crock-Linux** [comment]
bot-functions - 

 !info

TypeError: Cannot read properties of undefined (reading 'attributes')
    at Object.window.WAPI.window.WAPI.getHost (/home/whats/node_modules/@wppconnect-team/wppconnect/dist/lib/wapi/wapi.js:1:90432)
    at __puppeteer_evaluation_script__:56:59
    at __puppeteer_evaluation_script__:56:73
    at Y (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:2:388209)
    at new m (https://web.whatsapp.com/bootstrap_qr.daf26ac07924cd2f39eb.js:2:383177)
    at anonymous (__puppeteer_evaluation_script__:54:14)

**Comment by edgardmessias** [comment]
@Crock-Linux 
There are a better example of buttons here:

https://wppconnect-team.github.io/wppconnect/classes/Whatsapp.html#sendText

**Comment by Crock-Linux** [comment]
erro acontece no !info

**Comment by Crock-Linux** [comment]
so funciona no Whatsapp Business

**Pull request merged**
